### ISSUE TITLE
ubuntu-22.04 support

### ISSUE THREAD

**Issue by mscheltienne** [LABSN/sound-ci-helpers#6]
Hello, it looks like this is not working for the latest image.
I get a `sounddevice.PortAudioError: Error querying device -1` indicative of the absence of any output device.

**Comment by larsoner** [comment]
Quite likely some pulseaudio "stuff" needs to be started. Any interest in looking into it?

**Comment by mscheltienne** [comment]
Probably, but I have no idea how to debug it, I'm not that familiar with Linux.. I quickly tried via a GitHub codespace but did not figure out how to change the image from 20.04 to 22.04 😞 
For now, I downgraded the CIs image to 20.04.
